### ISSUE TITLE
Build in Docker Container

### ISSUE THREAD

**Issue by k4k** [kris-nova/kubicorn#119]
Continuing the discussion from #116.

I like the idea of implementing builds in docker containers for a number of reasons:

* Standardized build environment
* Standardized build tools (see conversation in #69)
* Simplified build process for those who don't want to setup a full dev environment
* Portability for Travis/Jenkins (maybe beneficial?)

We should still use a Makefile and allow users to build with `make` locally on their machines but providing a Dockerfile which will establish a known working build environment automatically and run `make` for you and for the platform you choose via a command line argument, would be very useful for new users and users on platforms that do not have easy access to tools we may choose to use as part of the build process.

**Comment by Ch3ck** [comment]
I'm looking at this issue @k4k @kris-nova @xmudrii What's required to complete this? I'll look at #69 and #116 and see what I can come up with
