### ISSUE TITLE
Headers are a bit weird

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#133]
Last night I was messing around with the new headers scripts and I was getting a *ton* of duplicate headers when running `make headers`

You should be able to pull from `master` and run `make headers` and see what I am talking about.

Can we get this cleaned up as our travis build now depends on it?

Thanks!

**Comment by kris-nova** [comment]
@xmudrii do you might taking a look here?

**Comment by xmudrii** [comment]
@kris-nova should be better with #133
