### ISSUE TITLE
Apply returns error: ssh: cannot decode encrypted private keys

### ISSUE THREAD

**Issue by xmudrii** [kris-nova/kubicorn#137]
I'm trying to create cluster on DO following [walkthrough](https://github.com/kris-nova/kubicorn/blob/master/docs/do/walkthrough.md).

Create command was successful:
```
10:34 in ~ on 🐳 v17.06.0-ce 
➜ kubicorn create --name myfirstk8s --profile do
2017-08-04T10:35:09+02:00 [✔]  Selected [fs] state store
2017-08-04T10:35:09+02:00 [✿]  The state [./_state/myfirstk8s/cluster.yaml] has been created. You can edit the file, then run `kubicorn apply -n myfirstk8s`
```
`_state/myfirstk8s/cluster.yaml` looks okay.

But when I try to `apply`:
```
10:45 in ~ on 🐳 v17.06.0-ce took 7s 
➜ kubicorn apply --name myfirstk8s                     
2017-08-04T10:45:17+02:00 [✔]  Selected [fs] state store
2017-08-04T10:45:17+02:00 [✔]  Loaded cluster: myfirstk8s
2017-08-04T10:45:17+02:00 [✔]  Init Cluster
2017-08-04T10:45:17+02:00 [✖]  ssh: cannot decode encrypted private keys
```

When I check my SSH keys this is what I see:
```
10:43 in ~ on 🐳 v17.06.0-ce 
➜ ls -al ~/.ssh/id_rsa*
-rw------- 1 marko marko 3.3K Aug  4 10:36 /home/marko/.ssh/id_rsa
-rw------- 1 marko marko  741 Aug  4 10:36 /home/marko/.ssh/id_rsa.pub
```
I tried adding it to the base using `ssh-add`:
```
ssh-add ~/.ssh/id_rsa
```
I changed SSH key path `_state/myfirstk8s/cluster.yaml` to another key which was already in base.
From:
```
...
 PublicKeyPath: ~/.ssh/id_rsa.pub
...
```
To:
```
Ssh:
  Identifier: ""
  Name: ""
  PublicKeyData: null
  PublicKeyFingerprint: ""
  PublicKeyPath: ~/.ssh/server_xmudrii_rsa.pub
  User: ubuntu
  metadata:
    creationTimestamp: null
```
No avail, still error. 
Keys are also added to my DigitalOcean account if that matters.

I tried to SSH into my Droplet using keys, and it works, without asking for password.
Here is details of other keys:
```
10:50 in ~ on 🐳 v17.06.0-ce 
➜ ls -al ~/.ssh/server_xmudrii_rsa*
-rw------- 1 marko marko 3.3K Jul 27 05:19 /home/marko/.ssh/server_xmudrii_rsa
-rw------- 1 marko marko  741 Jul 27 05:19 /home/marko/.ssh/server_xmudrii_rsa.pub
```

`echo $DIGITALOCEAN_ACCESS_TOKEN` returns my token which is valid (and tested).

Running latest Kubicorn built from latest master branch.
On Ubuntu 16.04.2, updated, with 4.10.0-28-generic kernel.

**Comment by looztra** [comment]
I faced the same problem.
I tried with a key not encrypted and it works.

To be noticed: the ssh key that you use must not be registred in digitalocean, `kubicorn` will do it for you (and fail if the key is already registred)

```shell
2017-08-04T14:37:56+02:00 [✖]  Error during apply! Attempting cleaning: POST https://api.digitalocean.com/v2/account/keys: 422 SSH Key is already in use on your account
```
So a temp workaround is to use unecrypted keys.

I'm not familiar with `golang.org/x/crypto/ssh` but would be happy to contribute so if anyone can give some hints/pointers, please do.

**Comment by xmudrii** [comment]
I believe second about linking SSH key to DO is bug as well. I think we're not supposed to create new pair of keys for the every cluster.

‎I'll take a look into this later, also in another issue you posted. Maybe I'll be able to trace down the issue.‎

**Comment by k4k** [comment]
We did not support keys with phassphrases for a while (see #76). But it was fixed (see https://github.com/kris-nova/kubicorn/pull/81). Perhaps there was a regression when we introduced ssh agent support (https://github.com/kris-nova/kubicorn/pull/102)?
