### ISSUE TITLE
Packet implementation

### ISSUE THREAD

**Issue by mhausenblas** [kris-nova/kubicorn#139]
It would be great if [Packet](https://www.packet.net) would be amongst the supported implementations.

**Comment by vielmetti** [comment]
Happy to help. @mhausenblas or @kris-nova do you have a suggested plan of attack for this?

**Comment by vielmetti** [comment]
@deitch wrote summary documentation for a plan of attack in #483, let's see how that moves forward.

**Comment by deitch** [comment]
It is in progress. I have about half of it done on a local branch. Figuring out some of the API and should be good.

**Comment by vielmetti** [comment]
@deitch has a PR in https://github.com/kris-nova/kubicorn/pull/486 that adds support for Packet.

**Comment by xmudrii** [comment]
Closed by #486 #491 #492
