### ISSUE TITLE
Sam says use semver!

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#14]
We need to make sure we uphold semver for `dep`

**Comment by MyDigitalLife** [comment]
What actually has te be done for this issue? As far as i know semver is just a set of rules you promise to uphold. So we would just need to add a .md talking about how we want to handle releases and BC breaks and stuff?

**Comment by kris-nova** [comment]
All we need to do is add documentation around versioning and what it means to the project
