### ISSUE TITLE
Commands on creation server

### ISSUE THREAD

**Issue by MyDigitalLife** [kris-nova/kubicorn#154]
DigitalOcean offers a the ability to show graphs about the CPU and disk I/O. For that to work you need to run this command on the server "curl -sSL https://agent.digitalocean.com/install.sh | sh". It would be nice if in the profiles we are able to add commands that need to be run on the servers as part of the setup process. It will probably come in handy for a lot more situations.

**Comment by xmudrii** [comment]
There is much better solution using the API. Changing something right now, will push PR

**Comment by kris-nova** [comment]
This is the point of the bootstrap scripts - we need to code this feature https://github.com/kris-nova/kubicorn/issues/41 and users can just bring their own bootstrap scripts

**Comment by kris-nova** [comment]
the scripts we offer in `/bootstrap` are supposed to be starting places - can we please add 2 more scripts that turn this feature on?

**Comment by kris-nova** [comment]
Do we think we need *another* place to define one off logic in the profile?

**Comment by xmudrii** [comment]
@kris-nova I'll push PR soon. That's good idea. I planned to use API on creation and to put it in state as option, but bootstrap script could be good as well.

The reason why I thought so is that user would be able to easier on/off it in state rather than changing script with command.

**Comment by MyDigitalLife** [comment]
With the changes we made to the scripts array to decouple meshbird this is a easy task. Just add a script and allow people to add it to there profile. Other types of monitoring could also be added easily. I'll add this tonight.

**Comment by kris-nova** [comment]
I think with the new direction of offering our own bootstrap scripts with the ability for users to pass in their own at runtime this issue is closed.. please re-open or correct me if this is not the case! 

Thanks everyone
