### ISSUE TITLE
Switch to CircleCI

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#157]
Travis hasn't been the most stable or reliable tool in the shed... can we give CircleCI a go?

**Comment by xmudrii** [comment]
I think we should give it a try. I think it could be even better than Travis is right now. 

Is it available like Travis as for free, or we have to self-host it?

**Comment by MyDigitalLife** [comment]
I just checked and CircleCi has a free tier. There are some limitation tho. 1,500 build minutes per month and up to 3 parallel builds for open source projects. It depends on the amount of pull requests but that could be a problem in the future. To get unlimited build minutes its 150$ per month. So looks like its a lot more expensive for a open source project then Travis.

**Comment by xmudrii** [comment]
That's not so bad, but still... When we implement all tests, let's say average build time is 3 minutes - we have 500 builds for month. As we have some more than 400 commits for first month, I think we would be in that frame. About 3 concurrent builds, not bad as well, I don't believe we need more right now.

There could be few workaround to improve it. Something like K8s or golang/go does with bots and tests. Only folks with specific permissions can run tests and when needed - e.g. you don't need to run build if somebody change doc or readme.

But... I don't know... Maybe we should still stick with Travis. Let's see how much builds we will need as project gets more popular as well as how much time it takes for build once we have all tests.

**Comment by zoidbergwill** [comment]
We could easily run them both for a while and see how it goes.

It'd be awesome if GCP/CNCF in the future provided CI to all popular projects relevant to their projects.

**Comment by MyDigitalLife** [comment]
I like that, no reason not to do it.
