### ISSUE TITLE
Add WeaveMesh VPN bootstrap script for DigitalOcean

### ISSUE THREAD

**Issue by xmudrii** [kris-nova/kubicorn#177]
Due to `meshbird` being not so good VPN solution (see issue #171), we need to offer multiple solutions.
WeaveMesh seems like a good solution - https://github.com/weaveworks/mesh

We need to see will it be okay for our need, create bootstrap script and test it.

Also see #178 for OpenVPN issue.

**Comment by kris-nova** [comment]
Any research here from anyone? Will this solve our problem?

**Comment by dpraburaj** [comment]
My understanding of k8s' networking(and networking in general) is very rudimentary but wonder if enabling WeaveNet's encryption(https://www.weave.works/docs/net/latest/concepts/encryption/) would make a VPN mesh like Meshbird unnecessary. 

As far as I understand, the control plane communication happens securely in kubeadm clusters by default and enabling weave net encryption(if one's using weave for overlay) would secure the data
data plane communication.

**Comment by xmudrii** [comment]
Duplicate of #415 

@dpraburaj I'll close this issue, as we have new one for this, #415
Basically, the biggest reason why we have VPN for DO is because Private Networking is not really "private".
Every Droplet from that Datacenter (even Droplets we don't own) can send/access our Droplets. So we wanted to increase security and we implemented VPNs.
However, with #407, we increased security by implementing Cloud Firewalls, so this is no a problem anymore.

More details is also available in issue #415

**Comment by fntlnz** [comment]
Another valid alternative could be wireguard: https://www.wireguard.com/

**Comment by xmudrii** [comment]
@fntlnz It looks good, however it looks like WeaveNet is better optimized for running on Kubernetes stack. I'll look around, this could be useful as well -- it seems like it's very easy to set up and configure it. Thanks a lot for the recommendation.
