### ISSUE TITLE
Add OpenVPN bootstrap script for DigitalOcean

### ISSUE THREAD

**Issue by xmudrii** [kris-nova/kubicorn#178]
Due to meshbird being not so good VPN solution (see issue #171), we need to offer multiple solutions.
OpenVPN is popular solution but we need to make it work in mesh mode so we actually get private networking. This [DO tutorial](https://www.digitalocean.com/community/tutorials/how-to-secure-traffic-between-vps-using-openvpn) and [this](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-16-04) could be a good starting point.

We need to see will it be okay for our need, create bootstrap script and test it.

Also see #177 for WeaveMesh.

**Comment by kris-nova** [comment]
This is prime bash hacking territory if we have any bash hackers among us!

**Comment by prateekgogia** [comment]
Hi, I can take a stab at it. Does it really have to be in bash ? I have some ideas to run openVPN in Docker containers with host networking and deploy using Kubernetes itself. Don't have the complete details yet, but if you think it will be something useful I can try to implement this.

**Comment by xmudrii** [comment]
Personally, I think we should stay with pure bash if that's possible. I believe that it could be easier for users to later change it per their needed with bash rather than with Docker. Also, we shouldn't mix implementations (e.g. one docker, one bash, another one something other).

**Comment by xmudrii** [comment]
I'm starting with this one. Nobody else started in meanwhile?
