### ISSUE TITLE
Don't delete resource if it existing before on account

### ISSUE THREAD

**Issue by xmudrii** [kris-nova/kubicorn#179]
Right now, depending on the resource, if it already exist in the account it will fail or that resource will be used.
For example, if you already had SSH key in account it would fail. That behavior was fixed in #155 - if SSH key already exist, use it.
The code checking does SSH key exist, and using it if it does can be found here https://github.com/kris-nova/kubicorn/blob/master/cloud/digitalocean/resources/ssh.go#L105

Problem is if you delete cluster (using `kubicorn delete`). In that case, even if key already existed, it will be deleted. Expected behavior is not to delete that key.
I'm not sure for tags, so we need to test it.

**Comment by MyDigitalLife** [comment]
In my dev environment I have the following situation:
First we do a create for the ssh key and that return a `SSH Key is already in use on your account` error.
Then knowing that a GetByFingerprint is performed. However this returns `The resource you were accessing could not be found.`.

**Comment by kris-nova** [comment]
Yeah this logic needs to be improved.. and I am okay with having `kubicorn` use keys that already exist (even though we should never be abandoning resources like that)

**Comment by xmudrii** [comment]
‎‎@mydigitallife If you didn't already deleted it, save it if you're able to do so. It would be useful later to test some changes when we improve error handling. 

I plan to push something tomorrow, which should better extend godo's responses.

**Comment by MyDigitalLife** [comment]
I still have the key so i'm able to test it if you push a change.

**Comment by xmudrii** [comment]
‎Sorry, it should be tonight or tomorrow, I have some work I must finish today.

**Comment by kris-nova** [comment]
So I think we should **only** focus on `ssh` keys to start, also I was able to code this into the `amazon` implementation in #162

**Comment by xmudrii** [comment]
@kris-nova do you want me to resolve it new PR or will we do it in #162 as well?

**Comment by xmudrii** [comment]
@kris-nova will try to fix it today as well :)

**Comment by kris-nova** [comment]
Isn't this closed?

**Comment by xmudrii** [comment]
This should be closed with Reconciler refactor we done in the past.
