### ISSUE TITLE
Add contributing workflow to docs

### ISSUE THREAD

**Issue by xmudrii** [kris-nova/kubicorn#180]
I think we should add document that will help users to contribute to the project. Doc should explain user what we expect in PR/review process and should explain how to do some actions. In my opinion it should have:
* Link to how to build `kubicorn`.
* Formatting code (`make gofmt`).
* Linting code (`make lint`).
* Vendoring dependecies (how to install dep, how to vendor, how to update)
* Adding headers to `*.go` files (`make check-header`, `make headers`).
* Maybe policy about testing stuff.

If you have suggestions, please leave them in comments.

**Comment by kris-nova** [comment]
Can we just expand this one? https://github.com/kris-nova/kubicorn/blob/master/CONTRIBUTING.md
