### ISSUE TITLE
We need the bootstrap script out of the repo

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#182]
Ideally we need `bootstrap/bootstrap.go` out of version control.. the problem is that if we do that it breaks `go get`...

Open to ideas/suggestions

**Comment by kris-nova** [comment]
We need to use `go generate` instead of having this in the makefile.. this now high priority as this is the most annoying part of the PR cycle

**Comment by gar** [comment]
It looks like this issue was resolved with 0916979cb468692677f6135043c31cd43fec7ce1. I think it can be closed?

**Comment by xmudrii** [comment]
@gar yep, thanks :)

Closed by #455.
