### ISSUE TITLE
Question: how to troubleshoot digitalocean SSH issues?

### ISSUE THREAD

**Issue by r0fls** [kris-nova/kubicorn#184]
I added my ssh key to digital ocean, and my DO token to my environment variables (while following the instructions from https://github.com/kris-nova/kubicorn/blob/master/docs/do/walkthrough.md). However I still get the below error:

```
$ kubicorn apply --name myfirstk8s
2017-08-06T22:22:38-07:00 [✔]  Selected [fs] state store
2017-08-06T22:22:38-07:00 [✔]  Loaded cluster: myfirstk8s
2017-08-06T22:22:38-07:00 [✔]  Init Cluster
2017-08-06T22:22:38-07:00 [✖]  ssh: no key found
```

Here's my ssh key fingerprint:

```
$ ssh-keygen -l -E md5 -f ~/.ssh/id_rsa.pub
2048 MD5:e4:11:46:d7:af:da:72:47:07:44:bf:a1:cf:da:f9:d7 
```

And as shown via DO:

<img width="809" alt="screen shot 2017-08-06 at 10 22 43 pm" src="https://user-images.githubusercontent.com/1858004/29013143-d7dc6848-7af5-11e7-957a-2530256046c8.png">

Are there any troubleshooting steps you recommend, or anything obvious I could be doing wrong? Thank you.

**Comment by kris-nova** [comment]
So the profile will look in `$HOME/.ssh/id_rsa.pub` for a key, if that doesn't exist it will error like that..

Fix 1: Copy/Create a key in that location on your file system
Fix 2: Change the profile after you create it to point to whichever key you want to use

I think the docs here are a little confusing - will update and hopefully clarify a few things

**Comment by r0fls** [comment]
Hmm my key is there: 

```
$ cat $HOME/.ssh/id_rsa.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCh+jEXeurMS4XeiSWjjx0VP/iYIUpbyjq8QQUfPoCKlaXl/3y2nmBm7lhKU8o3PsPoDr1ioLk9Z3O5bsM8d0LxW4MFUDA3tDwnmjChUyUGHgBqPnOB7y8Liq9D5zQDtl/pj9Div9VwUfvJGh1k332aHajmLaNvKR4JYn3mP7
BsYqcyFo8E6m+k1rRDwfBgHb8qOOffrNjMPzdF0NRAbWX4CbXQ0V0Q6vzDZvxZ8eP5ovDAbgEwwvvAtPX4Rxvi218/OOJPe3OzIN5BJCNMt1HMl9GDBUy0HRmBNPgnqdY+btmmqPP9W3bDGVgF1kLUSIWyNbI1fK8bvL5440Pi6xcj raphael.deem@Raphaels-MacBook-P
ro-2.local
```

**Comment by kris-nova** [comment]
Can you `ls -la` the file? Are owner/permissions correct?

**Comment by r0fls** [comment]
I get this:

```
 $ ls -la $HOME/.ssh/id_rsa.pub
-rw-r--r--  1 raphael.deem  staff  423 May 22 13:18 /Users/raphael.deem/.ssh/id_rsa.pub
```

Looks correct to me but I could be wrong...

**Comment by kris-nova** [comment]
`chmod 600 ~/.ssh/id_rsa.pub`?

**Comment by r0fls** [comment]
Still no love, I'm super confused... maybe should open a ticket with DO:

```
~/Documents/code $ chmod 600 ~/.ssh/id_rsa.pub
~/Documents/code $ kubicorn apply --name myfirstk8s
2017-08-06T23:10:36-07:00 [✔]  Selected [fs] state store
2017-08-06T23:10:36-07:00 [✔]  Loaded cluster: myfirstk8s
2017-08-06T23:10:36-07:00 [✔]  Init Cluster
2017-08-06T23:10:36-07:00 [✖]  ssh: no key found
```

**Comment by r0fls** [comment]
actually i guess that's probably some kind of bug since it's not even finding the key, at least based on the message 🤔

**Comment by kris-nova** [comment]
Do you have a private key there as well? This is the function that is failing btw: https://github.com/kris-nova/kubicorn/blob/master/cutil/initapi/ssh.go#L30

**Comment by kris-nova** [comment]
So it's looking for `$HOME/.ssh/id_rsa` as well

**Comment by r0fls** [comment]
Ya, I have it:

```
$ ls ~/.ssh/
config      id_rsa      id_rsa.pub  known_hosts
```

**Comment by kris-nova** [comment]
I know we had issues with larger/DSA keys in the past - is it a plain ol RSA key?

**Comment by r0fls** [comment]
It's 2048 bit length but that was the default when I generated it:

```
$ ssh-keygen -l -f ~/.ssh/id_rsa.pub
2048 SHA256:3M0z7e0u7Z6zEFGeEAZlU53mydwiVv3259PvKmLIjr8 raphael.deem@Raphaels-MacBook-Pro-2.local (RSA)
```

**Comment by kris-nova** [comment]
....this all looks completely reasonable

**Comment by kris-nova** [comment]
Version of `kubicorn`? You can get the commit shaw from running `kubicorn` with no args

**Comment by r0fls** [comment]
hmm wait, i'm an idiot... i think this is happening because i didn't update (i cloned this a while ago and then just reran `go get ...` but didn't reinstall or anything). Maybe I need to `go install ...` now?

**Comment by kris-nova** [comment]
you can run `make all` to recompile and drop off in `$GOPATH/bin/kubicorn`

**Comment by kris-nova** [comment]
Otherwise `make` will drop off in `$GOPATH/src/github.com/kris-nova/kubicorn/bin/kubicorn` and you can 
```bash
chmod +x $GOPATH/src/github.com/kris-nova/kubicorn/bin/kubicorn
mv $GOPATH/src/github.com/kris-nova/kubicorn/bin/kubicorn /usr/local/bin
```

**Comment by r0fls** [comment]
yay! 💯 still some other errors though :) I'll troubleshoot those but I think the original issue here is solved. Thanks again!! 😄

**Comment by kris-nova** [comment]
Closing - please open a new issue if you get snagged - and if you want to chat in slack instead of here I am always hanging in #kubicorn in gophers slack
