### ISSUE TITLE
Migrate progress indicator code into package

### ISSUE THREAD

**Issue by metmajer** [kris-nova/kubicorn#190]
In https://github.com/kris-nova/kubicorn/pull/172, we've added an anonymous function to [kubicorn/cmd/delete.sh](https://github.com/kris-nova/kubicorn/blob/2b2f39c8d2d163a42f471bdf33c73c1e0996da7f/cmd/delete.go#L112-L128), which indicates progress to a user during the execution of a long running task by repeatedly logging a symbol.

**Goals**
- Integrate this function into a package `sleeper` or similar.
- Symbol and interval (ms) shall be configurable.

@kris-nova and @xmudrii: Anything to add?

**Comment by metmajer** [comment]
Feel free to assign this to me.

**Comment by xmudrii** [comment]
This sounds like a good idea to me. :+1: :smile:

**Comment by kris-nova** [comment]
Also agree - please take a stab at coding this @metmajer!
