### ISSUE TITLE
Invalid command code when running the update headers script

### ISSUE THREAD

**Issue by boingram** [kris-nova/kubicorn#228]
$ make update-headers
    sed: 1: "./cutil/initapi/validat ...": invalid command code .

When running the update headers target after creating a new test file (cutil/initapi/validate_test.go), I received an invalid command code error when it tried to insert the header using sed. I was able to add it manually, but the error is probably worth fixing.

I linked the PR where the issue occurred below.

**Comment by aledbf** [comment]
@boingram are you using osx?

**Comment by boingram** [comment]
I am
