### ISSUE TITLE
Friends of Kubicorn

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#256]
As we move forward in our ongoing journey to unite the open source Kubernetes community.. we will need a place to show off the orgs/companies that we are working with!

Can we please offer a *Friends of Kubicorn* markdown file in `/docs`  that contains a list of projects we work well with and love?

Ideally the file would have the following:

1. Explanation on how to add your project to the file
2. A list of projects we love

For each project we love:

1. A logo
2. A brief description of what `kubicorn` can do with the project
3. Links to documentation on how to run `kubicorn` with the project

**Comment by ellenkorbes** [comment]
Idea: Have the website check that folder whenever it rebuilds and auto-add those projects there.

**Comment by ellenkorbes** [comment]
There's a section for it on the website now. Do we have any friends we wanna add there off the bat, or should I hide the section for now?

**Comment by kris-nova** [comment]
le closed - great job @ellenkorbes
