### ISSUE TITLE
go get has external dependency

### ISSUE THREAD

**Issue by prateekgogia** [kris-nova/kubicorn#257]
In [quick start](https://github.com/kris-nova/kubicorn/blob/master/docs/INSTALL.md#quickstart) we mention this command to get started -  `go get github.com/kris-nova/kubicorn`

This fails if the host doesn't have  `libncurses5-dev` library, either we should fix quick install guide or find a way around this dependency. Ubuntu 16.04 doesn't have this library, which causes go get to fail.

**Comment by kris-nova** [comment]
Also see #264 where we plan on offering releases instead of instructing users to `go get`

**Comment by kris-nova** [comment]
But in the mean time - we should probably should fix this

**Comment by xmudrii** [comment]
i sent a PR to lolgopher (kris-nova/lolgopher#14), which once vendored back to kubicorn should fix the problem

**Comment by kris-nova** [comment]
PR Merged https://github.com/kris-nova/lolgopher/pull/14
