### ISSUE TITLE
Should our API be immutable?

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#263]
One of the lessons prescribed in my book is that whenever infrastructure is mutated the current representation of the infrastructure should be destroyed and a new representation of the infrastructure should be created.

TLDR; I tell people we should have an immutable representation of infrastructure (API)

Wondering what folks think about implementing this into `kubicorn` as it would require a grander refactor of the `reconciler` work

**Comment by prateekgogia** [comment]
+1 for this, if it helps us add more test cases to our logic. Reconciler right now does need to be refactored, otherwise it will just keep growing.

**Comment by kris-nova** [comment]
Completely agree

**Comment by kris-nova** [comment]
CC @roberthbailey @pipejakob as this might impact their API work

**Comment by kris-nova** [comment]
@xmudrii and @prateekgogia can we open an issue with reconciler refactors we want?

**Comment by roberthbailey** [comment]
> the current representation of the infrastructure should be destroyed and a new representation of the infrastructure should be created.

How does that jive with supporting bare metal installations? Or does it only apply to IaaS environments where infrastructure resources are "infinitely" available?

On GKE we do something along these lines today with node upgrades -- when you change the k8s version on your nodes it requires creating an entirely new set of nodes. This makes it really simple to reason about the state of the nodes (they are always created from whole cloth at the specified version) but it leads to disruptive upgrades, when in many cases you could accomplish patch upgrades with a non-disruptive, in-place mechanism. 

Another lesson that we've learned is that if you do something like destroy and create an L7 load balancer (even if it's exactly the same definition) it can cause traffic to be dropped in the mean time making users of the system pretty unhappy. There's a difference between a pooled resource (like a VM) and a singleton resource (like an ingress object) so I don't think it's necessarily safe to apply the same logic to all cloud resources.
