### ISSUE TITLE
User feedback for delete command

### ISSUE THREAD

**Issue by k4k** [kris-nova/kubicorn#27]
Since delete takes a long time to complete there should be a spinner or some other visual confirmation of "I'm not dead"

**Comment by kris-nova** [comment]
I would like to implement a terminal spinner with `ncurses` and CGO... I know I am crazy.. but I would really like that in the project.

**Comment by kris-nova** [comment]
But we can just probably echo `.`'s or something...

**Comment by metmajer** [comment]
@k4k and @kris-nova: I'm on it! I'll push something and ask for your feedback very soon
