### ISSUE TITLE
Use public key hash for key name

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#279]
Right now we have an issue with flipping out public keys and using the same cluster name as defined in #274 

Can we please start changing how we name keys? Ideally we would take an `md5` (or some other algorithm I really don't care which) of the public key fingerprint and use that for the name of the key.

**Comment by mariomazo** [comment]
@kris-nova Maybe I misunderstood, but as I see it ,and my experience with hashicorp packer
is that at the end of the day you end with 200 resources, in this case 200 keypairs named as a hash. Doing the cleanup (in some sort of automatic way) is really difficult and potentially dangerous.

**Comment by matyix** [comment]
@kris-nova @mariomazo It wont be necessary to create unique key names - especially because of the cleanup related problems. The #269 now is sort of unrelated and it was due the fact that 
```
if isEqual {
	return applyResource, nil
}
``` 
never returned `true`, though the keys were identical, and `output, err := Sdk.Ec2.ImportKeyPair(input)` was always called and caused #269 although the keypair was already imported on AWS and could have been used.

By adding the checksum `PublicKeyFingerprint: known.SSH.PublicKeyFingerprint` now comparing the two keys are identical, thus the error should be fixed. 

```
expected := &KeyPair{
		Shared: Shared{
			Tags: map[string]string{
				"Name":              r.Name,
				"KubernetesCluster": known.Name,
			},
			CloudID:     known.SSH.Identifier,
			Name:        r.Name,
			TagResource: r.TagResource,
		},
		PublicKeyPath:        known.SSH.PublicKeyPath,
		PublicKeyData:        string(known.SSH.PublicKeyData),
		User:                 known.SSH.User,
		PublicKeyFingerprint: known.SSH.PublicKeyFingerprint,
	}
``` 

Once cleaned up and thoroughly tested will submit a PR which fixes #269 and #279.

**Comment by matyix** [comment]
@kris-nova There is another unique constraint, though - for SecurityGroup names within one VPC. 

```
InvalidGroup.Duplicate

You cannot create a security group with the same name as an existing security group in the same VPC, or the same region (EC2-Classic).
```

For this I am adding a time ordered UUID generator (under cutil package) and appending/using  this as the name of the security group. Are you OK with that? The generator looks stg like this - though can use any other UUID generator, should you suggest one - it's just the timer ordered the help listing.

```
// Generates a time ordered UUID. Top 32b timestamp bottom 96b random.
func TimeOrderedUUID() string {
	unixTime := uint32(time.Now().UTC().Unix())
	randomPart1 := rand.Uint32()
	randomPart2 := rand.Uint32()
	randomPart3 := rand.Uint32()
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%04x%08x",
		unixTime,
		uint16(randomPart1>>16),
		uint16(randomPart1&0xffff),
		uint16(randomPart2>>16),
		uint16(randomPart2&0xffff),
		randomPart3)
}
```

**Comment by matyix** [comment]
@kris-nova I think this can be closed now, as updates are not trying to re-create/upload a new key pair but can reuse an existing one.

**Comment by xmudrii** [comment]
With Reconciled and API refactor, this seems fixed.
@kris-nova if not, please reopen the issue :)

**Comment by matyix** [comment]
@xmudrii @kris-nova yes, this is fixed.
