### ISSUE TITLE
Force remove SSH keys

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#285]
Right now we hard code `force=false` for deleting keypairs. This means that we will always orphan a keypair in AWS if a user creates a cluster with a unique keypair and then destroys it after.

Can we please expose this flag via an environmental variable, document the environmental variable in `/docs/envvar.md`, and patch this?

Suggested variable name: `KUBICORN_FORCE_DELETE_KEY` 

The system as it stands today in AWS is here: https://github.com/kris-nova/kubicorn/blob/master/cloud/amazon/resources/keypair.go#L137-L151

**Comment by mariomazo** [comment]
I will take over this one!
