### ISSUE TITLE
Use unique name (within VPC/region) for a security group

### ISSUE THREAD

**Issue by matyix** [kris-nova/kubicorn#286]
SecurityGroup names within one VPC or region should be unique - currently we are using the name of the cluster, which makes deploying a cluster with the same name/or upscaling the cluster impossible due to duplicate name conflicts. From the AWS constraints lists:

```
InvalidGroup.Duplicate

You cannot create a security group with the same name as an existing security group in the same VPC, or the same region (EC2-Classic).
```

For this I am suggesting a time ordered UUID generator (under cutil package) and appending/using  this as the name of the security group. Are you OK with that? The generator looks stg like this - though can use any other UUID generator, should you suggest one - just choose the time ordered one as it helps with listing (when checking the AWS console).

```
// Generates a time ordered UUID. Top 32b timestamp bottom 96b random.
func TimeOrderedUUID() string {
	unixTime := uint32(time.Now().UTC().Unix())
	randomPart1 := rand.Uint32()
	randomPart2 := rand.Uint32()
	randomPart3 := rand.Uint32()
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%04x%08x",
		unixTime,
		uint16(randomPart1>>16),
		uint16(randomPart1&0xffff),
		uint16(randomPart2>>16),
		uint16(randomPart2&0xffff),
		randomPart3)
}
```

**Comment by kris-nova** [comment]
The proposal looks good - I just ask that we combine the cluster name with the UUID such as:

```go
uniqueName := fmt.Sprintf("%s-%s, clusterName, uuid)
```

Are you interested in implementing this change?
