### ISSUE TITLE
Refactor Cloud provider implementations for better tests and integration

### ISSUE THREAD

**Issue by prateekgogia** [kris-nova/kubicorn#288]
The `Reconciler` interface is good.. but we think we will need to move the `Reconciler` logic up a level so that it is globally used for each of the cloud provider implementations. After this is done a cloud provider will have to offer the following two components

1. A model (Note: we will need to structure the new cloud provider implementations to support multiple models)
2. A set of resources that are mapped in the model.

We will then pass the model to the reconciler, and the reconciler will parse the model *in the exact same way for every implementation*.

##### 1.  Shared logic for reconcilers.

The reconiler will live as a standalone package, and will have a new function called `SetModel(model [int]Resource)` that will take the model for each cloud implementation. 

*Question*: Do we want to use a new `type` for a model, instead of `map[int]Resource`?

2. Shared logic for signal handling.

Implement the improved signal handling of #267 into the newly created reconciler package.

3. Support more than one model per cloud provider as in GKE vs GCE

```
New directory structure:
.
└── cloud
    └── google
        ├── gce
        │   └── model.go
        └── gke
            └── model.go
```

4. Agree on new `Resources interface.

We have a proposal here: #273 and we need to reach an agreement.

5. Implement new interface for resources.

This is a dangerous and global refactor that will require a lot of work. But we need to do it now while we are still in Alpha. But after the new interface is agreed upon, we need to implement the new interface and harden our resource logic.

6. Add force delete, delete the profile completely regardless of failures.

Right now if one resource fails to delete, the entire delete operation fails. We would like a way to override this behavior to ignore errors and move on to the next resource. Very handy for developers who have failed a delete and are tired of manually cleaning up their clouds.

**Comment by kris-nova** [comment]
We also need  docs and tests on all of this :smile:

**Comment by prateekgogia** [comment]
> Question: Do we want to use a new type for a model, instead of map[int]Resource?

[]Resource{} (slice of Resource) ?
