### ISSUE TITLE
Force overwrite state store

### ISSUE THREAD

**Issue by mhausenblas** [kris-nova/kubicorn#32]
When doing a create in a directory where the state store already exists, the tool barks and stops:

```
$ kubicorn create --name myfirstk8s --profile aws
2017-07-15T16:17:11-06:00 [✖]  State store [myfirstk8s] exists, will not overwrite
```

The user at this moment does not have enough information to know how to overcome the situation, for example by removing the state store like so: `rm -R ./_state/myfirstk8s/`.

**Comment by kris-nova** [comment]
### Option 1)

Provide more detail in the error

### Option 2)

Add an `-i` interactive flag that will prompt a user for input to overwrite or not..


I vote 1

**Comment by mhausenblas** [comment]
Yes, Option 1 is fine with me. Should include instructions what to do next to fix the situation.

**Comment by kris-nova** [comment]
Do you want to take a crack at coding this?

**Comment by kris-nova** [comment]
# Changing the issue title as I think there is tangible work that needs to be done here:

1) Improve the error message when a state store already exists, with information on how to overcome the error

2) Add in an environmental variable that will allow users to **always** force overwrite state stores if set.

**Comment by kris-nova** [comment]
Should this be closed? I think so. Re open if necessary
