### ISSUE TITLE
What do we put on the website's footer?

### ISSUE THREAD

**Issue by ellenkorbes** [kris-nova/kubicorn#337]
Here:

![screenshot_20170825_213940](https://user-images.githubusercontent.com/25550091/29737037-f63bc58a-89dd-11e7-8169-c8ce17618468.png)

Ideas?

**Comment by kris-nova** [comment]
Link to our code of conduct?

**Comment by kris-nova** [comment]
can I PR this? how do I make a change?

**Comment by ellenkorbes** [comment]
Sorry, it's already bed time for me. You can do it, yes.

The file is https://github.com/kris-nova/kubicorn/blob/master/docs/_includes/footer.html

It's a three column layout. To put stuff in each column just add them...

```html
    <div class="col-4">
        HERE
    </div>
```
