### ISSUE TITLE
Do we want an author section at the bottom of our docs?

### ISSUE THREAD

**Issue by ellenkorbes** [kris-nova/kubicorn#338]
This:

![screenshot_20170825_214113](https://user-images.githubusercontent.com/25550091/29737090-a1d7844c-89de-11e7-8616-78da0b284808.png)

I think it'd work for posts or articles, but for documentation I'm not sure.

**Comment by xmudrii** [comment]
‎I would remove it from the website. Docs are contributed by many of us, and will probably be articles and posts as well (because it's generated of the md files in repo, right?). So, I think we can go without it.

**Comment by ellenkorbes** [comment]
We can have documentation *and* a separate section for posts or articles. For the latter I think this would look good. But yeah, okay, I'll remove it from the docs.

**Comment by kris-nova** [comment]
I think if someone wanted to author a blog or a tutorial it would make sense, but I would vote no author on docs for the reason @xmudrii mentioned.
