### ISSUE TITLE
Google Implementation 

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#34]
We need a starting point for Google

**Comment by shwsun** [comment]
Do you mean Google cloud?

**Comment by kris-nova** [comment]
Very much so.. We need GKE and GCE

**Comment by MyDigitalLife** [comment]
I'm working on the GCE implementation. I have creating and deleting of nodes working an will be starting the creation of the k8s cluster nest.

**Comment by xmudrii** [comment]
Closed by #266
