### ISSUE TITLE
Spot Price Validation

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#347]
Can we validate the spot price only is validated with AWS?

**Comment by ganlaksh** [comment]
@kris-nova : I can work on this one..

**Comment by matyix** [comment]
@ganlaksh I was working on #331 but currently away for a few days - please go ahead if you find the time to add the validation. Thank you.

**Comment by ganlaksh** [comment]
submitted PR #355 for this change

**Comment by xmudrii** [comment]
Closed by #355
