### ISSUE TITLE
Handling cloud provider specific API changes

### ISSUE THREAD

**Issue by matyix** [kris-nova/kubicorn#354]
Currently we have a lean and generic API - as we move towards supporting more and more use cases we hit the differences between cloud providers. 

An example is #331 where we introduced Spot price support (currently for AWS, but the GCP implementation will follow shortly) - and had an API change. A new feature I am about to introduce is IAM support (for AWS, and later for GCP) - it's the same as above and supported by/or differently by each/few providers. 

Is there a preferred way to move forward by keeping the API neat and clean but also support provider specific items? Any thoughts on this for the future? Thanks.

_I was trying to work around these and submit a few PRs in Kops for specific needs as such (like #https://github.com/kubernetes/kops/issues/2983) but ultimately found [Kubicorn](http://kubicorn.io) and never looked back ever since :)._

**Comment by kris-nova** [comment]
Ugh this is such a great issue. I think about this all the time. The two main approaches I have been toying with..


## 1 Cloud specific structs 

In the API we could have nullable cloud specific configuration such as

```go
type Cluster struct {
    Name string
    // other fields
    AwsConfiguration *AwsConfiguration
    // other cloud configurations
}

type AwsConfiguration struct {
    SpotPrice bool
}
```

## 2 Make them optional 

```go
type Cluster struct {
    Name string
    // other fields
    AwsSpotPrice bool
    // other optional fields
}
```

## My opinion

Go with option 1. I think it allows users to start coding in a ton of features and offers flexibility for clouds to grow.

###### Caveat 

I know spot price is cross-cloud - just using it as an easy-to-grok example

**Comment by MyDigitalLife** [comment]
I also like option 1.

**Comment by matyix** [comment]
Sounds good. Will refactor the spot feature and consider option 1 (which I prefer as well) when adding IAM support.

**Comment by matyix** [comment]
Closing as PR was merged.
