### ISSUE TITLE
kubicorn explain

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#359]
Using the reconciler pattern we can pull data about what is **Actually** running and what is **Expected** to be running...

Being able to run `kubicorn explain` and get a list of resources for each **actual** and **expected** would be handy!

We can output them as a table `-o table`
or as json `--output json` `-o json`
etc
etc

If you'd like to learn more about `kubicorn` project, you can read [The Project Walkthrough](http://kubicorn.io/documentation/readme.html).
If you have any question, comment on the issue, join us on the `#kubicorn` channel in the [Gophers Slack community](https://invite.slack.golangbridge.org/) or open a PR. We'll always do everything we can to get the PR though.

**Comment by xmudrii** [comment]
Working on this one :)

**Comment by xmudrii** [comment]
Submitted PR #509 that should fix this issue
