### ISSUE TITLE
Friends of kubicorn

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#363]
## Ark

Thanks to the fantastic works from our friends at Heptio, we can easily help you snapshot and recreate your entire `kubernetes` platform using Heptio's [Ark](https://github.com/heptio/ark)

![heptio-ark 1024px](https://user-images.githubusercontent.com/13757818/29894635-398dc41a-8d93-11e7-8101-b73336986bea.png)

## Calico

We use [Project Calico](https://www.projectcalico.org) to make **CNI** problems go away! Thanks to our friends at Tigera, we now can help you get kubernetes up and running in no time using a rock solid CNI provider.

![image](https://user-images.githubusercontent.com/13757818/29894798-f4608606-8d93-11e7-8418-d37f625d7140.png)

## Weave

We use [Weavenet](https://www.weave.works/oss/net) to help control our clusters! Thanks to our friends at Weave we now offer a great experience for networking in different clouds, and a seamless user experience. 

![image](https://user-images.githubusercontent.com/13757818/29909234-29de9f7c-8de2-11e7-9348-69289a54534a.png)

**Comment by kris-nova** [comment]
Actually - let's only put the project we are using and reference the company... so only use the project logo and leave the company ones out please!

**Comment by ellenkorbes** [comment]
What copy should I use next to the logo? `We use Heptio's Ark for our snapshots. And we would love to give Heptio and Ark credit.`?  Or something else?

**Comment by kris-nova** [comment]
See original message (I edited) but ideally we should all be able to make a change to the website and understand/know what goes where
