### ISSUE TITLE
Change site title and add favicon

### ISSUE THREAD

**Issue by xmudrii** [kris-nova/kubicorn#364]
I think we could change site title from `kubicorn` to something more descriptive, such as `kubicorn - Building Simple Kubernetes Infrastructure`.

Also, we could generate favicons from the project logo and add it to the site.

**Comment by ellenkorbes** [comment]
I've done the changes, but I used an automated favicon generator and I'm not sure it looks too well. Lemme know if you wanna try something else.

**Comment by xmudrii** [comment]
@ellenkorbes let's get it in and see how it looks
