### ISSUE TITLE
Add pre-release badge to kubicorn.io

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#379]
Can we please have some sort of noticable warning on the page that let's users know we are pre-release but working hard to get to `1.0.0`

We could add it to the [main page](http://kubicorn.io). [Here is the HTML file for the home page](https://github.com/kris-nova/kubicorn/blob/master/docs/_layouts/home.html).

If you'd like to learn more about `kubicorn` project, you can read [The Project Walkthrough](http://kubicorn.io/documentation/project-walkthrough.html).
If you have any question, comment on the issue, join us on the `#kubicorn` channel in the [Gophers Slack community](https://invite.slack.golangbridge.org/) or open a PR. We'll always do everything we can to get the PR though.

**Comment by Ch3ck** [comment]
HI @kris-nova @xmudrii I'll love to work on this issue

**Comment by xmudrii** [comment]
@Ch3ck Sounds great to me! If you need any help, feel free to ping me or @ellenkorbes here, or on the Slack.
