### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#38]
We need someone to build out the framework for github pages for

- kubicorn.com 
- kubicorn.io

**Comment by darron** [comment]
I can definitely help with getting it deployed and built with CI and stuff if that's not something that @mhausenblas wants to take on given what he was discussing today.

A couple questions though:

1. Where's the content for it? What needs to be on it?
2. Do we want to wait for the Gopher+🦄 thing.
3. I would recommend [Hugo](http://gohugo.io/) it works pretty well. The [last site I did](http://www.divescapes.ca/) was built and deployed from master - the code is pretty nice to work with. [Example](https://github.com/darron/divescapes.ca).
4. Is there somebody that can design it? I've been using [Hyde](https://github.com/enten/hyde-y) for the last [few](https://octohost.io/) personal [sites](https://blog.froese.org/) I've done but it's pretty basic.

Just throwing out a few ideas.

**Comment by mhausenblas** [comment]
If you have the cycles, more than happy for you to take care of it @darron ;)

**Comment by darron** [comment]
Sure - I have some cycles and this is probably a good place for me to start with respect to $dayjob issues.

**Comment by kris-nova** [comment]
> Where's the content for it? What needs to be on it?

We need to create it, ideally it would come from the repo's documentation / godocs

> Do we want to wait for the Gopher+🦄 thing.

Nah, we can add then it later. Besides I am sure @ashleymcnamara is swamped at the moment!

> I would recommend Hugo it works pretty well. The last site I did was built and deployed from master - the code is pretty nice to work with.

Sold.

> Is there somebody that can design it? I've been using Hyde for the last few personal sites I've done but it's pretty basic.

I am color blind and spend my life in the terminal so definitely not me. Open for suggestion and would prefer someone to own it and make it their own. Strong opinions welcomed.

**Comment by darron** [comment]
I made some progress on this today - ran into some CORS issues that I will need to sort out and just saw this comment now.

Will keep plugging away and have something shortish.

**Comment by shwsun** [comment]
Hi,
I am assuming that the most important part of the project page would be the documentation (and a decent way to render it) right? If so I think we can just adopt a something like  [slate](https://github.com/lord/slate) (or go doc)?

**Comment by kris-nova** [comment]
Is anyone actively working on this? I know we have https://github.com/kubicorn/www but I am not sure what the status is

**Comment by darron** [comment]
Hey @kris-nova I've been out on vacation, away from computers for a while and pretty slammed at work before I left for vacation.

I need to concentrate on other things for a while - so feel free to throw that away and start fresh.

Sorry I couldn't do more.

**Comment by kris-nova** [comment]
@darron okay thank you - and don't be sorry - we love all the work you did and appreciate it so much!

**Comment by ellenkorbes** [comment]
I'm on it :)

**Comment by kris-nova** [comment]
@ellenkorbes thank you so much for picking this up - let us know if chat how we can help

**Comment by ellenkorbes** [comment]
I'll share the final sketches tomorrow so y'all can help iron out the last details, then we can get to jekyll-ifying it during the week :)

**Comment by kris-nova** [comment]
Kubicorn.io is a thing - closing 😍😍
