### ISSUE TITLE
We need a getting started doc / asciinema

### ISSUE THREAD

**Issue by prateekgogia** [kris-nova/kubicorn#388]
Except `concepts` in Readme, we don't have any other way for a new user to start using Kubicorn. Some `gif` in Readme or getting started `doc` should help user getting started.

If you'd like to learn more about `kubicorn` project, you can read [The Project Walkthrough](http://kubicorn.io/documentation/readme.html).
If you have any question, comment on the issue, join us on the `#kubicorn` channel in the [Gophers Slack community](https://invite.slack.golangbridge.org/) or open a PR. We'll always do everything we can to get the PR though.

**Comment by krol3** [comment]
I will try to write some getting started doc

**Comment by xmudrii** [comment]
Closed by #463
