### ISSUE TITLE
Can't run pods on Digital Ocean

### ISSUE THREAD

**Issue by boingram** [kris-nova/kubicorn#392]
I've tried a few different pods/deployments/whatnots and can't get them to run when running the Ubuntu Digital Ocean profile using master.

As far as I can tell, it looks like Calico on the node gets stuck in a crash loop, preventing kube-dns from starting along with any other pods -- they all end up stuck in ContainerCreating.

When looking at Calico's logs (specifically the calico-node container), it looks like Calico unable to talk to etcd. kubectl was unable to get the logs, so I had to retrieve them directly from the node using `docker logs`. 

```
time="2017-09-13T02:14:02Z" level=info msg="NODENAME environment not specified - check HOSTNAME"
time="2017-09-13T02:14:02Z" level=info msg="Loading config from environment"
Skipping datastore connection test
time="2017-09-13T02:14:32Z" level=info msg="Unhandled error: client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint http://10.96.232.136:6666 exceeded header timeout
"
time="2017-09-13T02:14:32Z" level=info msg="Unable to query node configuration" Name=myfirstk8s-node-0 error="client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint http://10.96.232.136:6666 exceeded header timeout
"
Calico node failed to start
ERROR: Unable to access datastore to query node configuration
Terminating
```

**Comment by matyix** [comment]
@boingram I had similar problems on AWS - had to switch to Weave + and add ingress like this https://github.com/kris-nova/kubicorn/blob/master/profiles/centosamazon.go#L83. Note that the AWS profile on Master is not correct, as the ingress source CIDR is wrong - there is a [fix](https://github.com/kris-nova/kubicorn/pull/387) for this, though not merged yet. Applying the same for DO might make it work.

**Comment by kris-nova** [comment]
@boingram @matyix 

I think @matyix is right here and we will need a PR similar to #387 for DO.. Can somebody volunteer to code that please?

**Comment by xmudrii** [comment]
‎@kris-nova _raises hand_
Looking from the mobile, will #407 do the job?

**Comment by xmudrii** [comment]
@boingram @matyix is someone able to test this with the latest changes?

**Comment by boingram** [comment]
works for me now, I'll go ahead and close
