### ISSUE TITLE
Improve --set flag and implement it for the apply command

### ISSUE THREAD

**Issue by xmudrii** [kris-nova/kubicorn#417]
Currently, we have `--set` flag only implemented for the `create` command. We would like to have it for `apply` command as well.

But there as an bug in current implementation, which should be fixed before. As reported in the issue #381, current implementation is case sensitive, so if you execute:
```bash
kubicorn create knova -p azure --set location=uswest
```
It would fail. But if you execute
```bash
kubicorn create knova -p azure --set Location=uswest
```
It would work. It should work as expected with lower case too.

The [`helm`](https://github.com/kubernetes/helm) project implements something similar, so maybe it could be useful to take a look at their implementation. Their implementation is located [here](https://github.com/kubernetes/helm/blob/master/cmd/helm/install.go#L137).

Our current implementation is in the [`cmd/create.go`](https://github.com/kris-nova/kubicorn/blob/master/cmd/create.go#L149) file.

If you'd like to learn more about `kubicorn` project, you can read [The Project Walkthrough](http://kubicorn.io/documentation/project-walkthrough.html).
If you have any question, comment on the issue, join us on the `#kubicorn` channel in the [Gophers Slack community](https://invite.slack.golangbridge.org/) or open a PR. We'll always do everything we can to get the PR though.

**Comment by danicat** [comment]
@xmudrii the link to the project walkthrough in the issue description is broken (small typo on the `project` word) http://kubicorn.io/documentation/projetct-walkthrough.html -> http://kubicorn.io/documentation/project-walkthrough.html

**Comment by m4ns0ur** [comment]
@xmudrii you are using `swalker` dependency, which is case sensitive.
I don't no what is the edge cases here, but an easy fix is changing [L153](https://github.com/kris-nova/kubicorn/blob/master/cmd/create.go#L153) to this:
```
err := swalker.Write(strings.Title(parts[0]), newCluster, parts[1])
```

**Comment by xmudrii** [comment]
@m4ns0ur that could work, would you like to open a PR?

**Comment by m4ns0ur** [comment]
@xmudrii sure! Is there any related test on this file, to be updated?

**Comment by xmudrii** [comment]
@m4ns0ur nope, we don't have `cmd` related tests
