### ISSUE TITLE
We need a file parser

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#42]
We need a package/tool/etc that takes a string

`myString` *string* 

and attempts to turn it into another string

`myString` *string*

with the caveat being that we need the first string to represent **some** type of file resource, and the second string to represent it's content.

---

#### Examples:

`~/data` -> `content`
`/tmp/data` -> `content`
`http://nivenly.com/data` -> `content`
`https://nivenly.com/data` -> `content`
`s3://something/data` -> `content`

**Comment by mariomazo** [comment]
@kris-nova could you provide a sample of the ``data`` file. Is do we need some sort of parsing (remove \n and so on)

**Comment by kris-nova** [comment]
@mariomazo we should not alter the file in anyway, only read it to a variable. 

We just need to be able to give a function a string, and it either return a byte slice `[]byte` or an error `error`.

The accepted strings are listed above, but they could be something like the following:
`~/data` should read from `$HOME/data`
`/tmp/data` should read from `/tmp/data`
`http://nivenly.com/data` should send a GET HTTP request to `http://nivenly.com/data` and return the content
`https://nivenly.com/data` should send a GET HTTPs request to `https://nivenly.com/data` and return the content
`s3://something/data` should send a GET HTTPs request to the Amazon S3 endpoint `s3://something/data`

All we are offering is an ability for operators to define friendly strings, and get content from arbitrary locations. Does this make sense?

**Comment by mariomazo** [comment]
I will do it!
