### ISSUE TITLE
Include few lines about the website in our Project Walkthrough

### ISSUE THREAD

**Issue by xmudrii** [kris-nova/kubicorn#425]
We have the Project Walkthrough explaining everything newcomer contributors should know about the project.
I think we should include the several lines about the website's structure, e.g. which directories exist, where is the index page, where is the documentation and how everything should look like.

/Assigns @ellenkorbes

**Comment by kris-nova** [comment]
Yes I would love this as even I get confused... Maybe in the `README.md` in `/docs/`?

**Comment by ellenkorbes** [comment]
I was actually looking into this today but [stuff] got in the way. Will do
it first thing in the morning.
