### ISSUE TITLE
We need our API refactored

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#43]
So one of the main goals of the project is to ultimately consume a community standard API that will work with Google! 

The API is a work in progress that will live here: https://github.com/kris-nova/cluter-api

Furthermore, we need someone to audit and review this API, as it will be a good candidate for a starting point for the cluster API project. 

I kind of hate the words we use now to represent things, can we please change them? I am terrible at naming things.

**Comment by xmudrii** [comment]
Fixed with #162
