### ISSUE TITLE
Signal Handler Interface

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#44]
We need to create a global signal handler, that will reference an interface. Each reconciler should implement said interface so that we can handle POSIX signals globally.

If you are interested in coding we should talk, because I would want to hear your ideas! Otherwise I might just code this.

**Comment by kris-nova** [comment]
CC @geojaz because you are already in sighandler land 😄

**Comment by geojaz** [comment]
Yes I'm interested! :)

**Comment by kris-nova** [comment]
There are a lot of examples of interfaces all over the repo if you want to follow an existing pattern I am using.. otherwise we just need a way to specify a global signal handler interface that every reconciler can implement - so that we only have to write the signal catching portion of the code once.. and tell it which implementation to use :)

**Comment by kris-nova** [comment]
LMK if you need a hand/want to jump on a call

**Comment by kris-nova** [comment]
@xmudrii you may or may not write an interface depending on how you approach the problem - close this accordingly please
