### ISSUE TITLE
Add `--aws-profile` flag for selecting profile from the `~/.aws/credentials` file

### ISSUE THREAD

**Issue by xmudrii** [kris-nova/kubicorn#440]
In the PR #433, we've done several changes to allow usage of the `~/.aws/credentials` file. Parsing of the file is handled automatically, by the [`aws-sdk-go`](https://github.com/aws/aws-sdk-go). However, we have another problem now -- we can't specify the profile name, so it'll use the `default` profile every time.

[This document](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html) explains how you can configure the `aws-sdk-go` to use custom profile.

In order to fix this issue, you'll need to start with adding new flag in [`init function of apply.go file`](https://github.com/kris-nova/kubicorn/blob/master/cmd/apply.go#L65).

The rest of the implementation depends on the approach..
You can try adding `os.Setenv("AWS_PROFILE", flag_value)` to the `[Run function of Apply command](https://github.com/kris-nova/kubicorn/blob/master/cmd/apply.go#L46). If that works -- the PR is completed and you can create one.

If you'd like to learn more about `kubicorn` project, you can read [The Project Walkthrough](http://kubicorn.io/documentation/project-walkthrough.html).
If you have any question, comment on the issue, join us on the `#kubicorn` channel in the [Gophers Slack community](https://invite.slack.golangbridge.org/) or open a PR. We'll always do everything we can to get the PR though.

**Comment by Ch3ck** [comment]
@xmudrii I'll like to work on this issue, I currently see some PRs related to this issue. Is there anything in particular I should be looking at?

**Comment by xmudrii** [comment]
@Ch3ck #441 will close this once I merge it, so no, there's nothing needed around this issue.

**Comment by kris-nova** [comment]
Can we update he docs here too please?
