### ISSUE TITLE
[AWS Walkthrough] Update with the new way for obtaining credentials

### ISSUE THREAD

**Issue by fntlnz** [kris-nova/kubicorn#442]
In [Authenticating](https://github.com/kris-nova/kubicorn/blob/master/docs/_documentation/aws-walkthrough.md#authenticating), the AWS walkthrough only refers to `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.

This behavior has changed in #433 - also when #440 is done this document will need to be updated to reflect the new ways to pass the `--aws-profile` option.

**Comment by xmudrii** [comment]
Do you want to update it in the PR or to open new PR yourself?

Here are relevant files:
https://github.com/kris-nova/kubicorn/blob/master/docs/_documentation/aws-walkthrough.md
https://github.com/kris-nova/kubicorn/blob/master/docs/_documentation/envar.md

**Comment by fntlnz** [comment]
This has already been done in https://github.com/kris-nova/kubicorn/pull/434/files - sorry for duplicating. Did not notice, the `docs/docs_old` folder confused me 😕
