### ISSUE TITLE
Contributing file

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#45]
We need to document the contributing process

**Comment by darron** [comment]
And with that, maybe a Code of Conduct to set clear expectations.

**Comment by darron** [comment]
This seems to be pretty well written and used by some CNCF and Kubernetes projects:

http://contributor-covenant.org/version/1/4/

Anything missing from it that we'd need to add?

**Comment by jbeda** [comment]
Probably want to pick either DCO or CLA too to make sure that you have some process around contributions.  I have a bot for the DCO at least: https://github.com/heptio/sign-off-checker

**Comment by kris-nova** [comment]
I added https://github.com/kris-nova/kubicorn/blob/master/CODE_OF_CONDUCT.md and https://github.com/kris-nova/kubicorn/blob/master/CONTRIBUTING.md

The contributing one I typed up, but happy to change. Just wanted *something* in place as this repo is getting lots of good, but unexpected, attention.

**Comment by kris-nova** [comment]
Closing to keep issues tidy - please reopen if we need work done here
