### ISSUE TITLE
Reorganize profiles

### ISSUE THREAD

**Issue by xmudrii** [kris-nova/kubicorn#453]
Currently, [profiles](https://github.com/kris-nova/kubicorn/tree/master/profiles) are located all in the same directory, with format of `<os><provider>.go`.

That's not so easy to follow and as we add more stuff, it'll be hard to trace everything. 
We could split them in directories, such as:
```
/profiles/digitalocean/ubuntu_16_04
/profiles/azure/freebsd_11
```

If you're working on this one, make sure to update appropriate code and tests as well.
I know this is being used on at least two locations:
* [cmd/create.go](https://github.com/kris-nova/kubicorn/blob/master/cmd/create.go)
* [tests](https://github.com/kris-nova/kubicorn/tree/master/test)

If you'd like to learn more about `kubicorn` project, you can read [The Project Walkthrough](http://kubicorn.io/documentation/readme.html).
If you have any question, comment on the issue, join us on the `#kubicorn` channel in the [Gophers Slack community](https://invite.slack.golangbridge.org/) or open a PR. We'll always do everything we can to get the PR though.

**Comment by gar** [comment]
I'll take this, if that's okay?

**Comment by xmudrii** [comment]
Feel free to take it, sounds good to me

**Comment by samanthakem** [comment]
@gar are u working on this still?

**Comment by gar** [comment]
@samanthakem yes, and I hope to have a PR for it soon

**Comment by gar** [comment]
@xmudrii I've just opened a PR for this issue. Let me know if you have any comments or suggestions for changes I should make. Thanks! :)
