### ISSUE TITLE
Installing documentation

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#46]
We need docs on how to build/install/download this thing

**Comment by shwsun** [comment]
And maybe a way to render it? If so I recommend [slate](https://github.com/lord/slate)

**Comment by xmudrii** [comment]
@kris-nova I think it's already fixed with #53 
i'm just thinking should we explicitly write that you must have Go env installed until first version doesn't get released (and link to tutorial from golang.org)?

**Comment by xmudrii** [comment]
Closed with #53 and #147
