### ISSUE TITLE
Updating state store for cluster seems much slower than it was before

### ISSUE THREAD

**Issue by xmudrii** [kris-nova/kubicorn#461]

**Comment by lukasmalkmus** [comment]
Can confirm. I created a cluster on DigitalOcean with the default configuration on Monday and it worked perfectly. Today updating the cluster store timed out and failed. I will investigate further.

**Comment by xmudrii** [comment]
Works okay for me now. I'll close the issue. If anybody gets the problem, feel free to create new issue.
