### ISSUE TITLE
Make releases to make easy to package

### ISSUE THREAD

**Issue by joedborg** [kris-nova/kubicorn#470]
Hey!

Was looking to package this into Homebrew.  To make discrete releases, one seems to need GitHub releases.  I can then also do a Snap package for Linux.

**Comment by xmudrii** [comment]
We're planning to release the first GitHub release soon. We've got to check out some bugs and that should be it for the 0.1.00. Then, we can look into the integrating with Homebrew, Snap and probably AUR.

**Comment by joedborg** [comment]
Thanks @xmudrii!  If you remember, could you drop a comment on here when that is and I'll finish the two packages that I've started?  I'll keep watching too.

**Comment by xmudrii** [comment]
@joedborg No problem, I'll put a comment once it's released :)
