### ISSUE TITLE
install fails with `undefined: bootstrap.Asset`

### ISSUE THREAD

**Issue by paulczar** [kris-nova/kubicorn#51]
When I try to install I get an error about bootstap.Asset being undefined.  I believe its looking for a function inside the bootstrap.go file that was removed here - https://github.com/kris-nova/kubicorn/pull/21

```
$ go get github.com/kris-nova/kubicorn
# github.com/kris-nova/kubicorn/cloud/amazon/resources
../go/src/github.com/kris-nova/kubicorn/cloud/amazon/resources/launchconfiguration.go:165: undefined: bootstrap.Asset
```

**Comment by kris-nova** [comment]
Checking out now

**Comment by kris-nova** [comment]
I will open up another issue for the bootstrap.go concern now that we realize it's breaking `go get`

Thanks for finding this!
