### ISSUE TITLE
Add a flag or an environmental variable to choose between local and remote bootstrap script

### ISSUE THREAD

**Issue by xmudrii** [kris-nova/kubicorn#523]
Currently, when we apply a state, remote script (from GitHub) is used to reconcile the cluster. This is not always convenient, especially when modifying and testing scripts.

For example, we can add an environmental variable, such as `KUBICORN_DEVELOPMENT_MODE` and check for it when we parse state's bootstrap script in the `parser` package. If it's set, use the local script, if not, get it from the repository.

**Comment by adnxn** [comment]
I think a flag would be a better UX in this case since we're explicitly passing it in when running the `apply` command. What do you think?

**Comment by xmudrii** [comment]
@adnxn We can go with both. If you want to take over this one, I would be happy to instruct you what's needed to be done. :smile:

**Comment by adnxn** [comment]
@xmudrii, That would be great. Let me know please

**Comment by xmudrii** [comment]
@adnxn Sorry for the late update. I had to fix this, so I can rework and the DigitalOcean support. The fix is included in #527.

I would be happy to help you if you want to get started with any other issue! Just ping me on GitHub or Slack.
