### ISSUE TITLE
Implement CI/CD Testing

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#68]
I have a credit card, if you have skills and opinions!

### Goal

run `make test` for every PR and only allow merging on exit `0`

**Comment by jmcarp** [comment]
Do you have a preferred CI service?

**Comment by kris-nova** [comment]
@jmcarp just now seeing this - looks like @paulczar was able to add travis support for us. I have used it in the past and want to start there.

Do you have experience with any other CI/CD tools that you think would be helpful? I am asking because given the events of the bug in kubeadm today, I am realizing we REALLY need a rock solid build
