### ISSUE TITLE
We need a version bump make target

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#69]
Can we add 3 targets to the makefile?

1. Major version bump
2. Minor version bump
3. Patch version bump

They should all edit the `/VERSION` file

**Comment by k4k** [comment]
@kris-nova Pardon my ignorance here. Would this look something like `make VERSION=x.x.xxx` where the value of VERSION gets written to `/VERSION`? Or do you want something like `make VERSION=major` which increments the first position of the version number (eg. 0.0.001 -> 1.0.000), `VERSION=minor` bumping the second position and patch, the third?

**Comment by kris-nova** [comment]
I just want a simple way to bump the version up a value

# Patch bump

`0.0.001` -> `0.0.002`

# Minor bump

`0.0.001` -> `0.1.000`

# Major bump

`0.0.001` -> `1.0.000`

That way I can plug it into the release process and keep a tight grasp on version of the code.


This is low priority, as it's not TOO difficult to manually re-write the `/VERSION` file

**Comment by xmudrii** [comment]
Is black magic allowed (i.e. `awk` and `sed`)? That wouldn't work on Windows so there is problem already...
