### ISSUE TITLE
Can we make our github labels rainbow?

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#71]
Can someone who has opinions and can see color help me change the labels to a rainbow color theme?

**Comment by kris-nova** [comment]
@ellenkorbes you know I am looking right at you for this issue

**Comment by ellenkorbes** [comment]
Awesome 👩‍🎨

Right now I'm in tourist mode 🏟🏝 but I'll be back home tomorrow 🛬👩‍💻
