### ISSUE TITLE
ssh: cannot decode encrypted private keys

### ISSUE THREAD

**Issue by k4k** [kris-nova/kubicorn#76]
```
kubicorn getconfig -n attractive-badger -v4
2017-07-17T11:44:46-04:00 [✔]  Selected [fs] state store
2017-07-17T11:44:46-04:00 [✔]  Loaded cluster: attractive-badger
2017-07-17T11:44:46-04:00 [✔]  Init Cluster
2017-07-17T11:44:46-04:00 [▶]  Running preprocessors
2017-07-17T11:44:46-04:00 [✖]  ssh: cannot decode encrypted private keys
```

I believe this is related to: https://github.com/kris-nova/klone/issues/13

**Comment by k4k** [comment]
Confirmed with `dtruss` again that this is the same truncation behavior I saw in klone. Using a 2048bit key works, a 4096bit key fails and `dtruss` shows read() only copying in a partial key.

**Comment by k4k** [comment]
I looked at this more this morning. I believe my initial assessment to be incorrect both on this and https://github.com/kris-nova/klone/issues/13. I was digging through some of the libraries used and noticed a comment on `ssh.NewPublicKeys` which I had previously overlooked which explains this issue perfectly:

```
// NewPublicKeys returns a PublicKeys from a PEM encoded private key. An
// encryption password should be given if the pemBytes contains a password
// encrypted PEM block otherwise password should be empty. It supports RSA
// (PKCS#1), DSA (OpenSSL), and ECDSA private keys.
```

My 4096bit key was encrypted with a passphrase. I generated a 4096bit key without a passphrase and it works as expected. We should provide one or multiple of the following methods for this:

* Support ssh-agent
* Read password from flag
* Read password from env
* Detect presence of and prompt for passphrase

**Comment by k4k** [comment]
One slight modification to the above. We're using `golang/x/crypto` in kubicorn. While the technical details of the above apply to Klone only (using different ssh library), the reason behind the failure is the same. We are not asking for a passphrase. I should have a PR for this in the next day or two.

**Comment by kris-nova** [comment]
Excellent work! Thank you so much!
