### ISSUE TITLE
Hook up travis to our slack channel

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#94]
Can we please hook up travis to our slack channel? I would like somebody else owning the ci/cd stuff other me, so happy to give collab to another user.

**Comment by shwsun** [comment]
Is [it](https://docs.travis-ci.com/user/notifications/#Configuring-slack-notifications) ?

**Comment by k4k** [comment]
@shwsun Does this bypass the need to enable the Travis service as documented [here](https://blog.travis-ci.com/2014-03-13-slack-notifications/)?

**Comment by shwsun** [comment]
That blog is from 2014 so I not sure that would still be true. I think today it should be pretty easy to hook travis into slack :)

**Comment by kris-nova** [comment]
What are we blocked on here? I can get peeps on the phone if needed

**Comment by prateekgogia** [comment]
@kris-nova I tried to integrate this, looks like it is already enabled for Gophers team slack and travis notifications are sent to goa-builds channel. I don't know if we can hook it up to 2 travis and send notification to separate channels. It might also flood the chat with group messages, unless we want to have a separate channel for these notifications.

**Comment by kris-nova** [comment]
Okay let's close this for now and if we switch slack later we can re open then
